preset: 'none'

checkpoints: './checkpoints'
run_id: 'byol_run_01'

model:
    n_epochs: 250
    m: 0.996 # Controls EMA hyperparameter for BYOL momentum encoder
    m_decay: False

    architecture:
        preset: 'resnet18' # ['resnet18', 'resnet34', 'resnet50', 'none']
        features: 512     # Number of encoded features (null just uses original resnet output)
        downscale: True
        block_type: 'basic'
        layers: !!python/tuple [2, 2, 2, 2]

    projection_head:
        hidden: 512
        out: 256

    optimizer:
      type: 'sgd'
      lr: 0.2 # Note this will be scaled with batch_size so best to leave
      momentum: 0.9
      weight_decay: 0.0000015 # 0.0005
      beta_1: 0.9
      beta_2: 0.999
      lars: False
      trust_coef: 0.003

    scheduler:
      decay_type: 'warmupcosine' # ['none', 'cosine', 'warmupcosine']
      warmup_epochs: 10  # Only used in linear warmup cosine annealing, if scheduler type is 'warmupcosine'

data:
    color_channels: 1
    classes: 2
    rotate: True
    input_height: 128 # Keep this at 128 and adjust center_crop_size
    batch_size: 256 
    val_batch_size: 500
    cut_threshold: 20
    test_size: 0.2

## DATA ## 
augmentations:
  center_crop: 128
  random_crop: !!python/tuple [1.0, 1.0]

  rotation: False
  flip: False
  s: 0.0  # Set to 0 to disable colorjitter
  p_blur: 0.1 # set to 0 to disable blurring
  use_vae: True
